#!/usr/bin/env bash
THM="/usr/share/lightdm-webkit/themes"
CONF="/etc/lightdm/lightdm-webkit-greeter.conf"

if [ ! -d ${THM} ]
then
  sudo mkdir -p ${THM}
fi

sudo cp . ${THM}/

if [ -f ${CONF} ]
then
  sudo cp ${CONF} ${CONF}-bak
fi

config=`cat ${CONF}`
sudo echo ${config//^webkit-theme=(.*)$/lightwinter} >${CONF}

exit
